//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentNScoot.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RentNScoot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roller Abgeben ähnelt.
        /// </summary>
        public static string CviMain_Back_1 {
            get {
                return ResourceManager.GetString("CviMain_Back_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurück ähnelt.
        /// </summary>
        public static string CviMain_Back_2 {
            get {
                return ResourceManager.GetString("CviMain_Back_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roller Mieten ähnelt.
        /// </summary>
        public static string CviMain_Continue_1 {
            get {
                return ResourceManager.GetString("CviMain_Continue_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zum nächsten Schritt ähnelt.
        /// </summary>
        public static string CviMain_Continue_2 {
            get {
                return ResourceManager.GetString("CviMain_Continue_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daten bestätigen ähnelt.
        /// </summary>
        public static string CviMain_Continue_3 {
            get {
                return ResourceManager.GetString("CviMain_Continue_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programm schließen ähnelt.
        /// </summary>
        public static string CviMain_Continue_4 {
            get {
                return ResourceManager.GetString("CviMain_Continue_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wir überprüfen deine Zahlung... ähnelt.
        /// </summary>
        public static string CviMain_Err_Payment {
            get {
                return ResourceManager.GetString("CviMain_Err_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähle einen Standort aus ähnelt.
        /// </summary>
        public static string CviMain_LocationFrame_ChooseAnOptionAlert {
            get {
                return ResourceManager.GetString("CviMain_LocationFrame_ChooseAnOptionAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uns Fehlen noch Daten von dir. Bitte fülle die Felder aus ähnelt.
        /// </summary>
        public static string CviMain_PersonalDataFrame_NotAllFieldsSetAlert {
            get {
                return ResourceManager.GetString("CviMain_PersonalDataFrame_NotAllFieldsSetAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rückgabe abschließen ähnelt.
        /// </summary>
        public static string CviMain_RentalResult_Back {
            get {
                return ResourceManager.GetString("CviMain_RentalResult_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rental Code überprüfen ähnelt.
        /// </summary>
        public static string CviMain_RentalResult_RentalCode {
            get {
                return ResourceManager.GetString("CviMain_RentalResult_RentalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähle einen Scooter aus ähnelt.
        /// </summary>
        public static string CviMain_ScooterFrame_ChooseAnOptionAlert {
            get {
                return ResourceManager.GetString("CviMain_ScooterFrame_ChooseAnOptionAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte prüfe die Verfügbarkeit eines Rollers an deinem Datum ähnelt.
        /// </summary>
        public static string CviMain_TimeFrame_NoAcceptedDateAlert {
            get {
                return ResourceManager.GetString("CviMain_TimeFrame_NoAcceptedDateAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gab Probleme mit deinem Rental Code, probiere es bitte später erneut oder wende dich an unseren Support. Fehler 105 ähnelt.
        /// </summary>
        public static string CvmMain_Err_RentalCodeError {
            get {
                return ResourceManager.GetString("CvmMain_Err_RentalCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Etwas stimmt mit deinem Rental Code nicht. Wir beenden den Prozess, probiere es bitte erneut ähnelt.
        /// </summary>
        public static string CvmMain_Err_RentalCodeNotExistent {
            get {
                return ResourceManager.GetString("CvmMain_Err_RentalCodeNotExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wählen einen unserer Standorte ähnelt.
        /// </summary>
        public static string LocationFrame_Headline {
            get {
                return ResourceManager.GetString("LocationFrame_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähle maximal 1 Standort aus. Um den ausgewählten Standort zurückzusetzten klicke ihn erneut an. ähnelt.
        /// </summary>
        public static string LocationFrame_TooManLocationsAlert {
            get {
                return ResourceManager.GetString("LocationFrame_TooManLocationsAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Übersicht, hier muss alles stimmen... ähnelt.
        /// </summary>
        public static string OverviewFrame_Headline {
            get {
                return ResourceManager.GetString("OverviewFrame_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abholort: ähnelt.
        /// </summary>
        public static string OverviewFrame_Location {
            get {
                return ResourceManager.GetString("OverviewFrame_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 21220 Hamburg, Dresslerstraße 12 ähnelt.
        /// </summary>
        public static string OverviewFrame_Location_Placeholder {
            get {
                return ResourceManager.GetString("OverviewFrame_Location_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Daten: ähnelt.
        /// </summary>
        public static string OverviewFrame_PersonalData {
            get {
                return ResourceManager.GetString("OverviewFrame_PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adresse: ähnelt.
        /// </summary>
        public static string OverviewFrame_PersonalData_Address {
            get {
                return ResourceManager.GetString("OverviewFrame_PersonalData_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 11111 Musterstadt, Musterstraße 54A ähnelt.
        /// </summary>
        public static string OverviewFrame_PersonalData_Address_Placeholder {
            get {
                return ResourceManager.GetString("OverviewFrame_PersonalData_Address_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string OverviewFrame_PersonalData_Name {
            get {
                return ResourceManager.GetString("OverviewFrame_PersonalData_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Mustermann ähnelt.
        /// </summary>
        public static string OverviewFrame_PersonalData_Name_Placeholder {
            get {
                return ResourceManager.GetString("OverviewFrame_PersonalData_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zahlungsmethode: ähnelt.
        /// </summary>
        public static string OverviewFrame_PersonalData_Payment {
            get {
                return ResourceManager.GetString("OverviewFrame_PersonalData_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorrauszahlung ähnelt.
        /// </summary>
        public static string OverviewFrame_PersonalData_Payment_Placeholder {
            get {
                return ResourceManager.GetString("OverviewFrame_PersonalData_Payment_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scooter: ähnelt.
        /// </summary>
        public static string OverviewFrame_Scooter {
            get {
                return ResourceManager.GetString("OverviewFrame_Scooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Xiaomi Mi Electric Scooter 1S ähnelt.
        /// </summary>
        public static string OverviewFrame_Scooter_Placeholder {
            get {
                return ResourceManager.GetString("OverviewFrame_Scooter_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abholung am: ähnelt.
        /// </summary>
        public static string OverviewFrame_TimeSpanFrom {
            get {
                return ResourceManager.GetString("OverviewFrame_TimeSpanFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 21.12.2021 um 9:00 Uhr ähnelt.
        /// </summary>
        public static string OverviewFrame_TimeSpanFrom_Placeholder {
            get {
                return ResourceManager.GetString("OverviewFrame_TimeSpanFrom_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rückgabe am: ähnelt.
        /// </summary>
        public static string OverviewFrame_TimeSpanTo {
            get {
                return ResourceManager.GetString("OverviewFrame_TimeSpanTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 22.12.2021 um 9:00 Uhr ähnelt.
        /// </summary>
        public static string OverviewFrame_TimeSpanTo_Placeholder {
            get {
                return ResourceManager.GetString("OverviewFrame_TimeSpanTo_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Barzahlung: ähnelt.
        /// </summary>
        public static string PaymentMethod_Cash {
            get {
                return ResourceManager.GetString("PaymentMethod_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kreditkarte: ähnelt.
        /// </summary>
        public static string PaymentMethod_Credit {
            get {
                return ResourceManager.GetString("PaymentMethod_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Klarna: ähnelt.
        /// </summary>
        public static string PaymentMethod_Klarna {
            get {
                return ResourceManager.GetString("PaymentMethod_Klarna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paypal: ähnelt.
        /// </summary>
        public static string PaymentMethod_Paypal {
            get {
                return ResourceManager.GetString("PaymentMethod_Paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorrauszahlung: ähnelt.
        /// </summary>
        public static string PaymentMethod_UpFront {
            get {
                return ResourceManager.GetString("PaymentMethod_UpFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stadt: ähnelt.
        /// </summary>
        public static string PersonalData_City {
            get {
                return ResourceManager.GetString("PersonalData_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Musterstadt ähnelt.
        /// </summary>
        public static string PersonalData_CityExample {
            get {
                return ResourceManager.GetString("PersonalData_CityExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorname: ähnelt.
        /// </summary>
        public static string PersonalData_FirstName {
            get {
                return ResourceManager.GetString("PersonalData_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max ähnelt.
        /// </summary>
        public static string PersonalData_FirstNameExample {
            get {
                return ResourceManager.GetString("PersonalData_FirstNameExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wir bräuchten noch ein Paar Daten... ähnelt.
        /// </summary>
        public static string PersonalData_Headline {
            get {
                return ResourceManager.GetString("PersonalData_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hausnummer: ähnelt.
        /// </summary>
        public static string PersonalData_Number {
            get {
                return ResourceManager.GetString("PersonalData_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 54A ähnelt.
        /// </summary>
        public static string PersonalData_NumberExample {
            get {
                return ResourceManager.GetString("PersonalData_NumberExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zahlungsmethode: ähnelt.
        /// </summary>
        public static string PersonalData_PaymentMethod {
            get {
                return ResourceManager.GetString("PersonalData_PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Barzahlung ähnelt.
        /// </summary>
        public static string PersonalData_PaymentMethod_Cash {
            get {
                return ResourceManager.GetString("PersonalData_PaymentMethod_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bezahle bei der Abholung deines Scooters im Laden. Mit EC-Karte oder Bargeld. ähnelt.
        /// </summary>
        public static string PersonalData_PaymentMethod_Cash_Hint {
            get {
                return ResourceManager.GetString("PersonalData_PaymentMethod_Cash_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kreditkarte ähnelt.
        /// </summary>
        public static string PersonalData_PaymentMethod_CreditCard {
            get {
                return ResourceManager.GetString("PersonalData_PaymentMethod_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du wirst nach Abschluss des Mietvorganges im Browser auf die Seite unseres sicheren Kreditkartendienstleisters weitergeleitet. ähnelt.
        /// </summary>
        public static string PersonalData_PaymentMethod_CreditCard_Hint {
            get {
                return ResourceManager.GetString("PersonalData_PaymentMethod_CreditCard_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Klarna ähnelt.
        /// </summary>
        public static string PersonalData_PaymentMethod_Klarna {
            get {
                return ResourceManager.GetString("PersonalData_PaymentMethod_Klarna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du wirst nach Abschluss des Mietvorganges im Browser auf die Seite von Klarna weitergeleitet. ähnelt.
        /// </summary>
        public static string PersonalData_PaymentMethod_Klarna_Hint {
            get {
                return ResourceManager.GetString("PersonalData_PaymentMethod_Klarna_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paypal ähnelt.
        /// </summary>
        public static string PersonalData_PaymentMethod_Paypal {
            get {
                return ResourceManager.GetString("PersonalData_PaymentMethod_Paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du wirst nach Abschluss des Mietvorganges im Browser auf die Seite von Paypal weitergeileitet. ähnelt.
        /// </summary>
        public static string PersonalData_PaymentMethod_Paypal_Hint {
            get {
                return ResourceManager.GetString("PersonalData_PaymentMethod_Paypal_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorrauszahlung ähnelt.
        /// </summary>
        public static string PersonalData_PaymentMethod_UpFront {
            get {
                return ResourceManager.GetString("PersonalData_PaymentMethod_UpFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zahle einfach per Überweisung und hole deinen Scooter schnell und unkompliziert ab. Nach Abschluss der Reservierung leiten wir dich dafür auf die Seite unseres Finanzinstitutes weiter. ähnelt.
        /// </summary>
        public static string PersonalData_PaymentMethod_UpFront_Hint {
            get {
                return ResourceManager.GetString("PersonalData_PaymentMethod_UpFront_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PLZ: ähnelt.
        /// </summary>
        public static string PersonalData_PostalCode {
            get {
                return ResourceManager.GetString("PersonalData_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 21035 ähnelt.
        /// </summary>
        public static string PersonalData_PostalCode_Example {
            get {
                return ResourceManager.GetString("PersonalData_PostalCode_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mustermann ähnelt.
        /// </summary>
        public static string PersonalData_SecondNameExample {
            get {
                return ResourceManager.GetString("PersonalData_SecondNameExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nachname: ähnelt.
        /// </summary>
        public static string PersonalData_SeconName {
            get {
                return ResourceManager.GetString("PersonalData_SeconName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Straße: ähnelt.
        /// </summary>
        public static string PersonalData_Street {
            get {
                return ResourceManager.GetString("PersonalData_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Musterstraße ähnelt.
        /// </summary>
        public static string PersonalData_StreetExample {
            get {
                return ResourceManager.GetString("PersonalData_StreetExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Reservierung wurde getätigt... ähnelt.
        /// </summary>
        public static string RentalDetailFrame {
            get {
                return ResourceManager.GetString("RentalDetailFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infos zu deiner Zahlungsmethode: ähnelt.
        /// </summary>
        public static string RentalDetailFrame_PaymentMethod {
            get {
                return ResourceManager.GetString("RentalDetailFrame_PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast Barzahlung als Zahlungsmittel ausgewählt. Erscheine dafür bitte rechtzeitig in unserem Laden und zahle deine Mietgebühr. Solltest du zu spät erscheinen wird deine Reservierung storniert. ähnelt.
        /// </summary>
        public static string RentalDetailFrame_PaymentMethodInfo_Cash {
            get {
                return ResourceManager.GetString("RentalDetailFrame_PaymentMethodInfo_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast bezahlung per Kreditkarte als zahlungsmethode gewählt. Wir leiten dich in kürze weiter auf die Seite unseres Kreditinstitutes... ähnelt.
        /// </summary>
        public static string RentalDetailFrame_PaymentMethodInfo_CreditCard {
            get {
                return ResourceManager.GetString("RentalDetailFrame_PaymentMethodInfo_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast Klarna als Zahlungsmethode gewählt. Wir leiten dich in kürze auf die Klarna Seite weiter... ähnelt.
        /// </summary>
        public static string RentalDetailFrame_PaymentMethodInfo_Klarna {
            get {
                return ResourceManager.GetString("RentalDetailFrame_PaymentMethodInfo_Klarna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast Paypal als Zahlungsmethode gewählt. Wir leiten dich in kürze weiter zu Paypal... ähnelt.
        /// </summary>
        public static string RentalDetailFrame_PaymentMethodInfo_Paypal {
            get {
                return ResourceManager.GetString("RentalDetailFrame_PaymentMethodInfo_Paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast Vorrauszahlung als Zahlungsmethode gewählt. Wir leiten dich gleich auf die Seite unseres Finanzdienstleisters weiter. ähnelt.
        /// </summary>
        public static string RentalDetailFrame_PaymentMethodInfo_UpFront {
            get {
                return ResourceManager.GetString("RentalDetailFrame_PaymentMethodInfo_UpFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das ist dein Rental Code, speichere ihn dir gut ab, du brauchst ihn um deinen Roller wieder abzugeben. ähnelt.
        /// </summary>
        public static string RentalDetailFrame_RentalCodeHint {
            get {
                return ResourceManager.GetString("RentalDetailFrame_RentalCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte trage einen Rental Code ein ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Err_RentalCodeEmpty {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Err_RentalCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der eingetragene Rental Code ist ungültig ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Err_RentalCodeInvalid {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Err_RentalCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gebe deinen Roller ab ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Headline {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trage dazu bitte hier deinen Rental Code ein: ähnelt.
        /// </summary>
        public static string RentalReturnFrame_PostCodeHere {
            get {
                return ResourceManager.GetString("RentalReturnFrame_PostCodeHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo xxxxx xxxxx, hier ist deine Abgabe Übersicht: ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Summary_HeadlineInfo_Placeholder {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Summary_HeadlineInfo_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Summary_HeadlineInfo1 {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Summary_HeadlineInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die , hier ist deine Abgabe Übersicht: ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Summary_HeadlineInfo2 {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Summary_HeadlineInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die und sich dein Roller am richtigen Abgabeort: xxxxx xxxxx, xxxxxxxxxx x befindet. ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Summary_LocationInfo_Placeholder {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Summary_LocationInfo_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die und sich dein Roller am richtigen Abgabeort: ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Summary_LocationInfo1 {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Summary_LocationInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die befindet. ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Summary_LocationInfo2 {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Summary_LocationInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte stelle sicher das die Bezahlung stattgefunden hat ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Summary_PaymentInfo {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Summary_PaymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Mietvorgang ist hiermit abgeschlossen, bei Problemen melden wir uns bei dir. ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Summary_RentalProcess {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Summary_RentalProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vielen Dank das du mit uns gescootet bist, kehre mit Rückgabe abschließen zur Übersicht zurück. ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Summary_RentalProcessEnd {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Summary_RentalProcessEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hattest deinen xxxxxx für xx Tage, dies kostet dich xxx Euro ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Summary_ScooterInfo_Placeholder {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Summary_ScooterInfo_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hattest deinen ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Summary_ScooterInfo1 {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Summary_ScooterInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die für ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Summary_ScooterInfo2 {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Summary_ScooterInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stunden. ähnelt.
        /// </summary>
        public static string RentalReturnFrame_Summary_ScooterInfo3 {
            get {
                return ResourceManager.GetString("RentalReturnFrame_Summary_ScooterInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Such dir einen Roller aus ähnelt.
        /// </summary>
        public static string ScooterFrame_Headline {
            get {
                return ResourceManager.GetString("ScooterFrame_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähle maximal 1 Scooter aus. Um den ausgewählten Scooter zurückzusetzten klicke ihn erneut an. ähnelt.
        /// </summary>
        public static string ScooterFrame_ToManScootersAlert {
            get {
                return ResourceManager.GetString("ScooterFrame_ToManScootersAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verfügbarkeit prüfen ähnelt.
        /// </summary>
        public static string TimeFrame_CheckDateButton {
            get {
                return ResourceManager.GetString("TimeFrame_CheckDateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Datum ist nicht korrekt ähnelt.
        /// </summary>
        public static string TimeFrame_DateMissingAlert {
            get {
                return ResourceManager.GetString("TimeFrame_DateMissingAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du gibst den Roller ab bevor du ihn abholst? ähnelt.
        /// </summary>
        public static string TimeFrame_DatesMixedAlert {
            get {
                return ResourceManager.GetString("TimeFrame_DatesMixedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte vervollständige deine Daten ähnelt.
        /// </summary>
        public static string TimeFrame_EmptyFieldsAlert {
            get {
                return ResourceManager.GetString("TimeFrame_EmptyFieldsAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wann willst du ihn abholen ähnelt.
        /// </summary>
        public static string TimeFrame_From {
            get {
                return ResourceManager.GetString("TimeFrame_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Von Wann bis Wann willst du mieten? ähnelt.
        /// </summary>
        public static string TimeFrame_Headline {
            get {
                return ResourceManager.GetString("TimeFrame_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wir Teilen den Tag in Abhol und Rückgabezeiten auf. Damit du deinen Roller schnell bekommst und direkt loslegen kannst wähle bitte eine Zeit aus. Keine Sorge wir reservieren dir den Scooter für 30 Minuten. Solltest du nicht im Laden bezahlen wird bei nichterscheinen 30 Minuten nach deinem Termin mit der Abrechnung begonnen, sollte du nicht vorher abgesagt haben. ähnelt.
        /// </summary>
        public static string TimeFrame_HintText {
            get {
                return ResourceManager.GetString("TimeFrame_HintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wofür die Zeitangabe ähnelt.
        /// </summary>
        public static string TimeFrame_HintTitle {
            get {
                return ResourceManager.GetString("TimeFrame_HintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es fehlt eine Zeit ähnelt.
        /// </summary>
        public static string TimeFrame_TimeMissingAlert {
            get {
                return ResourceManager.GetString("TimeFrame_TimeMissingAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wann willst du ihn zurückbringen ähnelt.
        /// </summary>
        public static string TimeFrame_To {
            get {
                return ResourceManager.GetString("TimeFrame_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die angeben ähnelt.
        /// </summary>
        public static string WelcomeFrame_DataCard_Choose {
            get {
                return ResourceManager.GetString("WelcomeFrame_DataCard_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daten ähnelt.
        /// </summary>
        public static string WelcomeFrame_DataCard_Data {
            get {
                return ResourceManager.GetString("WelcomeFrame_DataCard_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen bei RentNScoot ähnelt.
        /// </summary>
        public static string WelcomeFrame_Headline {
            get {
                return ResourceManager.GetString("WelcomeFrame_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Mobilität für nur 3,99€ die Stunde ähnelt.
        /// </summary>
        public static string WelcomeFrame_HeadlineUnderline {
            get {
                return ResourceManager.GetString("WelcomeFrame_HeadlineUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wählen ähnelt.
        /// </summary>
        public static string WelcomeFrame_LocationCard_Choose {
            get {
                return ResourceManager.GetString("WelcomeFrame_LocationCard_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location ähnelt.
        /// </summary>
        public static string WelcomeFrame_LocationCard_Location {
            get {
                return ResourceManager.GetString("WelcomeFrame_LocationCard_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fahren ähnelt.
        /// </summary>
        public static string WelcomeFrame_ReadyCard_Choose {
            get {
                return ResourceManager.GetString("WelcomeFrame_ReadyCard_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die abholen ähnelt.
        /// </summary>
        public static string WelcomeFrame_ReadyCard_Ready {
            get {
                return ResourceManager.GetString("WelcomeFrame_ReadyCard_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die aussuchen ähnelt.
        /// </summary>
        public static string WelcomeFrame_ScooterCard_Choose {
            get {
                return ResourceManager.GetString("WelcomeFrame_ScooterCard_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scooter ähnelt.
        /// </summary>
        public static string WelcomeFrame_ScooterCard_Scooter {
            get {
                return ResourceManager.GetString("WelcomeFrame_ScooterCard_Scooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die festlegen ähnelt.
        /// </summary>
        public static string WelcomeFrame_TimeCard_Choose {
            get {
                return ResourceManager.GetString("WelcomeFrame_TimeCard_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeitraum ähnelt.
        /// </summary>
        public static string WelcomeFrame_TimeCard_Time {
            get {
                return ResourceManager.GetString("WelcomeFrame_TimeCard_Time", resourceCulture);
            }
        }
    }
}
